// pokemondata.js

export const pokemons = [
  {
    "id": 25,
    "name": "Pikachu",
    "type": "Electric",
    "imageUrl": "https://img.pokemondb.net/artwork/large/pikachu.jpg",
    "link": "https://pokemondb.net/pokedex/pikachu",
    "description": "Pikachu is an Electric-type Pokémon, which was introduced in Generation I.",
    "abilities": ["Static", "Lightning Rod"],
    "rarity": "Common",
    "strength": 55
  },
  // Continue adding Pokemon objects till dex no 151...
  {
    "id": 28,
    "name": "Sandslash",
    "type": "Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/sandslash.jpg",
    "link": "https://pokemondb.net/pokedex/sandslash",
    "description": "Sandslash's hard and sharp claws can easily cut through the toughest of surfaces. It lives in arid regions.",
    "abilities": ["Sand Veil", "Sand Rush"],
    "rarity": "Uncommon",
    "strength": 75
  },
  {
    "id": 29,
    "name": "Nidoran♀",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/nidoran-f.jpg",
    "link": "https://pokemondb.net/pokedex/nidoran-f",
    "description": "Nidoran♀ has large ears that it uses to sense danger. When threatened, it raises its ears and releases a poisonous barb from its horn.",
    "abilities": ["Poison Point", "Rivalry"],
    "rarity": "Common",
    "strength": 55
  },
  {
    "id": 30,
    "name": "Nidorina",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/nidorina.jpg",
    "link": "https://pokemondb.net/pokedex/nidorina",
    "description": "When Nidorina are with their friends or family, they keep their barbs tucked away to prevent injury. They will only use them when threatened.",
    "abilities": ["Poison Point", "Rivalry"],
    "rarity": "Uncommon",
    "strength": 70
  },
  {
    "id": 31,
    "name": "Nidoqueen",
    "type": "Poison/Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/nidoqueen.jpg",
    "link": "https://pokemondb.net/pokedex/nidoqueen",
    "description": "Nidoqueen is known for its immense power and protective instincts. It uses its scaly hide to shield its young from harm.",
    "abilities": ["Poison Point", "Rivalry"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 32,
    "name": "Nidoran♂",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/nidoran-m.jpg",
    "link": "https://pokemondb.net/pokedex/nidoran-m",
    "description": "Nidoran♂ has a horn that secretes a powerful venom. Its small size allows it to evade predators by hiding in tall grass.",
    "abilities": ["Poison Point", "Rivalry"],
    "rarity": "Common",
    "strength": 46
  },
  {
    "id": 33,
    "name": "Nidorino",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/nidorino.jpg",
    "link": "https://pokemondb.net/pokedex/nidorino",
    "description": "Nidorino's horn contains venom so powerful that it can even kill larger creatures. It uses its horn for both offense and defense.",
    "abilities": ["Poison Point", "Rivalry"],
    "rarity": "Uncommon",
    "strength": 61
  },
  {
    "id": 34,
    "name": "Nidoking",
    "type": "Poison/Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/nidoking.jpg",
    "link": "https://pokemondb.net/pokedex/nidoking",
    "description": "Nidoking is known for its brutal power and incredible strength. It can topple buildings with a single blow of its tail.",
    "abilities": ["Poison Point", "Rivalry"],
    "rarity": "Rare",
    "strength": 81
  },
  {
    "id": 35,
    "name": "Clefairy",
    "type": "Fairy",
    "imageUrl": "https://img.pokemondb.net/artwork/large/clefairy.jpg",
    "link": "https://pokemondb.net/pokedex/clefairy",
    "description": "Clefairy is a Fairy-type Pokémon known for its love of dancing in the moonlight. It is said to bring good fortune to those who encounter it.",
    "abilities": ["Cute Charm", "Magic Guard"],
    "rarity": "Uncommon",
    "strength": 70
  },
  {
    "id": 36,
    "name": "Clefable",
    "type": "Fairy",
    "imageUrl": "https://img.pokemondb.net/artwork/large/clefable.jpg",
    "link": "https://pokemondb.net/pokedex/clefable",
    "description": "Clefable is a Fairy-type Pokémon known for its serene and calm demeanor. It is said to live in quiet, remote areas.",
    "abilities": ["Cute Charm", "Magic Guard"],
    "rarity": "Rare",
    "strength": 95
  },
  {
    "id": 37,
    "name": "Vulpix",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/vulpix.jpg",
    "link": "https://pokemondb.net/pokedex/vulpix",
    "description": "Vulpix is a Fire-type Pokémon known for its beautiful, flowing mane of fur. It can manipulate fire to create dazzling displays.",
    "abilities": ["Flash Fire", "Drought"],
    "rarity": "Common",
    "strength": 38
  },
  {
    "id": 38,
    "name": "Ninetales",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/ninetales.jpg",
    "link": "https://pokemondb.net/pokedex/ninetales",
    "description": "Ninetales is a Fire-type Pokémon known for its elegant and mystical appearance. It is said to have the power to control the weather.",
    "abilities": ["Flash Fire", "Drought"],
    "rarity": "Rare",
    "strength": 73
  },
  {
    "id": 39,
    "name": "Jigglypuff",
    "type": "Normal/Fairy",
    "imageUrl": "https://img.pokemondb.net/artwork/large/jigglypuff.jpg",
    "link": "https://pokemondb.net/pokedex/jigglypuff",
    "description": "Jigglypuff is a Normal/Fairy-type Pokémon known for its soothing lullabies. It uses its voice to put its foes to sleep.",
    "abilities": ["Cute Charm", "Competitive"],
    "rarity": "Uncommon",
    "strength": 115
  },
  {
    "id": 40,
    "name": "Wigglytuff",
    "type": "Normal/Fairy",
    "imageUrl": "https://img.pokemondb.net/artwork/large/wigglytuff.jpg",
    "link": "https://pokemondb.net/pokedex/wigglytuff",
    "description": "Wigglytuff is a Normal/Fairy-type Pokémon known for its powerful vocal cords. Its singing can reach distances over a mile away.",
    "abilities": ["Cute Charm", "Competitive"],
    "rarity": "Rare",
    "strength": 140
  },
  {
    "id": 41,
    "name": "Zubat",
    "type": "Poison/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/zubat.jpg",
    "link": "https://pokemondb.net/pokedex/zubat",
    "description": "Zubat is a Poison/Flying-type Pokémon known for its echolocation abilities. It can navigate in complete darkness using sound waves.",
    "abilities": ["Inner Focus", "Infiltrator"],
    "rarity": "Common",
    "strength": 40
  },
  {
    "id": 42,
    "name": "Golbat",
    "type": "Poison/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/golbat.jpg",
    "link": "https://pokemondb.net/pokedex/golbat",
    "description": "Golbat is a Poison/Flying-type Pokémon known for its large wingspan. It can fly for hours without tiring.",
    "abilities": ["Inner Focus", "Infiltrator"],
    "rarity": "Uncommon",
    "strength": 75
  },
  {
    "id": 43,
    "name": "Oddish",
    "type": "Grass/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/oddish.jpg",
    "link": "https://pokemondb.net/pokedex/oddish",
    "description": "Oddish is a Grass/Poison-type Pokémon known for its nocturnal habits. It releases a strong aroma to attract other Oddish.",
    "abilities": ["Chlorophyll", "Run Away"],
    "rarity": "Common",
    "strength": 45
  },
  {
    "id": 44,
    "name": "Gloom",
    "type": "Grass/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/gloom.jpg",
    "link": "https://pokemondb.net/pokedex/gloom",
    "description": "Gloom is a Grass/Poison-type Pokémon known for its putrid smell. It releases a foul odor when it feels threatened.",
    "abilities": ["Chlorophyll", "Stench"],
    "rarity": "Uncommon",
    "strength": 60
  },
  {
    "id": 45,
    "name": "Vileplume",
    "type": "Grass/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/vileplume.jpg",
    "link": "https://pokemondb.net/pokedex/vileplume",
    "description": "Vileplume is a Grass/Poison-type Pokémon known for its stunning appearance. Its petals release a sweet fragrance that attracts prey.",
    "abilities": ["Chlorophyll", "Effect Spore"],
    "rarity": "Rare",
    "strength": 75
  },
  {
    "id": 46,
    "name": "Paras",
    "type": "Bug/Grass",
    "imageUrl": "https://img.pokemondb.net/artwork/large/paras.jpg",
    "link": "https://pokemondb.net/pokedex/paras",
    "description": "Paras is a Bug/Grass-type Pokémon known for its parasitic behavior. It attaches itself to larger Pokémon and drains their nutrients.",
    "abilities": ["Effect Spore", "Dry Skin"],
    "rarity": "Common",
    "strength": 35
  },
  {
    "id": 47,
    "name": "Parasect",
    "type": "Bug/Grass",
    "imageUrl": "https://img.pokemondb.net/artwork/large/parasect.jpg",
    "link": "https://pokemondb.net/pokedex/parasect",
    "description": "Parasect is a Bug/Grass-type Pokémon known for its symbiotic relationship with Paras. It becomes more aggressive when it senses danger.",
    "abilities": ["Effect Spore", "Dry Skin"],
    "rarity": "Uncommon",
    "strength": 60
  },
  {
    "id": 48,
    "name": "Venonat",
    "type": "Bug/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/venonat.jpg",
    "link": "https://pokemondb.net/pokedex/venonat",
    "description": "Venonat is a Bug/Poison-type Pokémon known for its large, compound eyes. It can see in complete darkness.",
    "abilities": ["Compound Eyes", "Tinted Lens"],
    "rarity": "Common",
    "strength": 60
  },
  {
    "id": 49,
    "name": "Venomoth",
    "type": "Bug/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/venomoth.jpg",
    "link": "https://pokemondb.net/pokedex/venomoth",
    "description": "Venomoth is a Bug/Poison-type Pokémon known for its ability to release powders that induce sleep. It is often found in forests.",
    "abilities": ["Shield Dust", "Tinted Lens"],
    "rarity": "Uncommon",
    "strength": 70
  },
  {
    "id": 50,
    "name": "Diglett",
    "type": "Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/diglett.jpg",
    "link": "https://pokemondb.net/pokedex/diglett",
    "description": "Diglett is a Ground-type Pokémon known for its burrowing abilities. It can dig tunnels at speeds of over 60 mph.",
    "abilities": ["Sand Veil", "Arena Trap"],
    "rarity": "Common",
    "strength": 55
  },
  {
    "id": 51,
    "name": "Dugtrio",
    "type": "Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/dugtrio.jpg",
    "link": "https://pokemondb.net/pokedex/dugtrio",
    "description": "Dugtrio is the evolved form of Diglett. It is known for its ability to burrow underground at incredible speeds.",
    "abilities": ["Sand Veil", "Arena Trap"],
    "rarity": "Uncommon",
    "strength": 80
  },
  {
    "id": 52,
    "name": "Meowth",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/meowth.jpg",
    "link": "https://pokemondb.net/pokedex/meowth",
    "description": "Meowth is a Normal-type Pokémon known for its cunning and mischievous behavior. It is often found in urban areas.",
    "abilities": ["Pickup", "Technician"],
    "rarity": "Common",
    "strength": 45
  },
  {
    "id": 53,
    "name": "Persian",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/persian.jpg",
    "link": "https://pokemondb.net/pokedex/persian",
    "description": "Persian is the evolved form of Meowth. It is known for its grace and agility, as well as its sharp claws.",
    "abilities": ["Limber", "Technician"],
    "rarity": "Uncommon",
    "strength": 70
  },
  {
    "id": 54,
    "name": "Psyduck",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/psyduck.jpg",
    "link": "https://pokemondb.net/pokedex/psyduck",
    "description": "Psyduck is a Water-type Pokémon known for its constant headache. When its headache worsens, it unleashes powerful psychic energy.",
    "abilities": ["Damp", "Cloud Nine"],
    "rarity": "Common",
    "strength": 50
  },
  {
    "id": 55,
    "name": "Golduck",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/golduck.jpg",
    "link": "https://pokemondb.net/pokedex/golduck",
    "description": "Golduck is a Water-type Pokémon known for its strong psychic powers. It can read minds and predict its opponents' moves.",
    "abilities": ["Damp", "Cloud Nine"],
    "rarity": "Uncommon",
    "strength": 80
  },
  {
    "id": 56,
    "name": "Mankey",
    "type": "Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/mankey.jpg",
    "link": "https://pokemondb.net/pokedex/mankey",
    "description": "Mankey is a Fighting-type Pokémon known for its short temper. It can fly into a rage at the slightest provocation.",
    "abilities": ["Vital Spirit", "Anger Point"],
    "rarity": "Common",
    "strength": 60
  },
  {
    "id": 57,
    "name": "Primeape",
    "type": "Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/primeape.jpg",
    "link": "https://pokemondb.net/pokedex/primeape",
    "description": "Primeape is the evolved form of Mankey. Its rage knows no bounds, and it will attack anything that crosses its path.",
    "abilities": ["Vital Spirit", "Anger Point"],
    "rarity": "Uncommon",
    "strength": 90
  },
  {
    "id": 58,
    "name": "Growlithe",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/growlithe.jpg",
    "link": "https://pokemondb.net/pokedex/growlithe",
    "description": "Growlithe is a Fire-type Pokémon known for its loyalty and bravery. It will protect its Trainer at all costs.",
    "abilities": ["Intimidate", "Flash Fire"],
    "rarity": "Common",
    "strength": 55
  },
  {
    "id": 59,
    "name": "Arcanine",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/arcanine.jpg",
    "link": "https://pokemondb.net/pokedex/arcanine",
    "description": "Arcanine is the evolved form of Growlithe. It is known for its incredible speed and power, as well as its noble and majestic appearance.",
    "abilities": ["Intimidate", "Flash Fire"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 60,
    "name": "Poliwag",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/poliwag.jpg",
    "link": "https://pokemondb.net/pokedex/poliwag",
    "description": "Poliwag is a Water-type Pokémon known for its unique spiral pattern. It uses this pattern to confuse its enemies.",
    "abilities": ["Water Absorb", "Damp"],
    "rarity": "Common",
    "strength": 40
  },
  {
    "id": 61,
    "name": "Poliwhirl",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/poliwhirl.jpg",
    "link": "https://pokemondb.net/pokedex/poliwhirl",
    "description": "Poliwhirl is the evolved form of Poliwag. It is known for its powerful arms, which it uses to swim through even the strongest currents.",
    "abilities": ["Water Absorb", "Damp"],
    "rarity": "Uncommon",
    "strength": 65
  },
  {
    "id": 62,
    "name": "Poliwrath",
    "type": "Water/Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/poliwrath.jpg",
    "link": "https://pokemondb.net/pokedex/poliwrath",
    "description": "Poliwrath is the evolved form of Poliwhirl. It is known for its incredible strength and fighting prowess.",
    "abilities": ["Water Absorb", "Damp"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 63,
    "name": "Abra",
    "type": "Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/abra.jpg",
    "link": "https://pokemondb.net/pokedex/abra",
    "description": "Abra is a Psychic-type Pokémon known for its ability to teleport. It is often found in urban areas.",
    "abilities": ["Synchronize", "Inner Focus"],
    "rarity": "Common",
    "strength": 20
  },
  {
    "id": 64,
    "name": "Kadabra",
    "type": "Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/kadabra.jpg",
    "link": "https://pokemondb.net/pokedex/kadabra",
    "description": "Kadabra is the evolved form of Abra. It is known for its incredible psychic powers, which it uses to bend spoons and levitate objects.",
    "abilities": ["Synchronize", "Inner Focus"],
    "rarity": "Uncommon",
    "strength": 40
  },
  {
    "id": 65,
    "name": "Alakazam",
    "type": "Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/alakazam.jpg",
    "link": "https://pokemondb.net/pokedex/alakazam",
    "description": "Alakazam is the final evolved form of Abra. It is known for its incredible intellect and psychic powers.",
    "abilities": ["Synchronize", "Inner Focus"],
    "rarity": "Rare",
    "strength": 55
  },
  {
    "id": 66,
    "name": "Machop",
    "type": "Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/machop.jpg",
    "link": "https://pokemondb.net/pokedex/machop",
    "description": "Machop is a Fighting-type Pokémon known for its incredible strength and endurance. It can lift heavy objects with ease.",
    "abilities": ["Guts", "No Guard"],
    "rarity": "Common",
    "strength": 70
  },
  {
    "id": 67,
    "name": "Machoke",
    "type": "Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/machoke.jpg",
    "link": "https://pokemondb.net/pokedex/machoke",
    "description": "Machoke is the evolved form of Machop. It is known for its incredible muscle mass and power.",
    "abilities": ["Guts", "No Guard"],
    "rarity": "Uncommon",
    "strength": 80
  },
  {
    "id": 68,
    "name": "Machamp",
    "type": "Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/machamp.jpg",
    "link": "https://pokemondb.net/pokedex/machamp",
    "description": "Machamp is the final evolved form of Machop. It is known for its incredible fighting prowess and four powerful arms.",
    "abilities": ["Guts", "No Guard"],
    "rarity": "Rare",
    "strength": 100
  },
  {
    "id": 69,
    "name": "Bellsprout",
    "type": "Grass/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/bellsprout.jpg",
    "link": "https://pokemondb.net/pokedex/bellsprout",
    "description": "Bellsprout is a Grass/Poison-type Pokémon known for its sharp teeth and acidic saliva. It captures prey by ensnaring them with its vines.",
    "abilities": ["Chlorophyll", "Gluttony"],
    "rarity": "Common",
    "strength": 50
  },
  {
    "id": 70,
    "name": "Weepinbell",
    "type": "Grass/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/weepinbell.jpg",
    "link": "https://pokemondb.net/pokedex/weepinbell",
    "description": "Weepinbell is the evolved form of Bellsprout. It is known for its powerful digestive juices, which it uses to dissolve its prey.",
    "abilities": ["Chlorophyll", "Gluttony"],
    "rarity": "Uncommon",
    "strength": 65
  },
  {
    "id": 71,
    "name": "Victreebel",
    "type": "Grass/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/victreebel.jpg",
    "link": "https://pokemondb.net/pokedex/victreebel",
    "description": "Victreebel is the final evolved form of Bellsprout. It is known for its massive jaws and the sweet-smelling nectar it produces.",
    "abilities": ["Chlorophyll", "Gluttony"],
    "rarity": "Rare",
    "strength": 80
  },
  {
    "id": 72,
    "name": "Tentacool",
    "type": "Water/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/tentacool.jpg",
    "link": "https://pokemondb.net/pokedex/tentacool",
    "description": "Tentacool is a Water/Poison-type Pokémon known for its gelatinous body and poisonous tentacles. It can deliver a painful sting with its tentacles.",
    "abilities": ["Clear Body", "Liquid Ooze"],
    "rarity": "Common",
    "strength": 40
  },
  {
    "id": 73,
    "name": "Tentacruel",
    "type": "Water/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/tentacruel.jpg",
    "link": "https://pokemondb.net/pokedex/tentacruel",
    "description": "Tentacruel is the final evolved form of Tentacool. It is known for its massive size and powerful tentacles, which it uses to capture prey.",
    "abilities": ["Clear Body", "Liquid Ooze"],
    "rarity": "Uncommon",
    "strength": 80
  },
  {
    "id": 74,
    "name": "Geodude",
    "type": "Rock/Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/geodude.jpg",
    "link": "https://pokemondb.net/pokedex/geodude",
    "description": "Geodude is a Rock/Ground-type Pokémon known for its rocky exterior and incredible strength. It can easily crush boulders with its powerful arms.",
    "abilities": ["Rock Head", "Sturdy"],
    "rarity": "Common",
    "strength": 55
  },
  {
    "id": 75,
    "name": "Graveler",
    "type": "Rock/Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/graveler.jpg",
    "link": "https://pokemondb.net/pokedex/graveler",
    "description": "Graveler is the evolved form of Geodude. It is known for its massive size and powerful physique.",
    "abilities": ["Rock Head", "Sturdy"],
    "rarity": "Uncommon",
    "strength": 70
  },
  {
    "id": 76,
    "name": "Golem",
    "type": "Rock/Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/golem.jpg",
    "link": "https://pokemondb.net/pokedex/golem",
    "description": "Golem is the final evolved form of Geodude. It is known for its immense strength and ability to roll down mountains without slowing down.",
    "abilities": ["Rock Head", "Sturdy"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 77,
    "name": "Ponyta",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/ponyta.jpg",
    "link": "https://pokemondb.net/pokedex/ponyta",
    "description": "Ponyta is a Fire-type Pokémon known for its incredible speed and agility. It can run faster than the wind.",
    "abilities": ["Run Away", "Flash Fire"],
    "rarity": "Common",
    "strength": 65
  },
  {
    "id": 78,
    "name": "Rapidash",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/rapidash.jpg",
    "link": "https://pokemondb.net/pokedex/rapidash",
    "description": "Rapidash is the evolved form of Ponyta. It is known for its blazing speed and the flames that trail behind it.",
    "abilities": ["Run Away", "Flash Fire"],
    "rarity": "Uncommon",
    "strength": 90
  },
  {
    "id": 79,
    "name": "Slowpoke",
    "type": "Water/Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/slowpoke.jpg",
    "link": "https://pokemondb.net/pokedex/slowpoke",
    "description": "Slowpoke is a Water/Psychic-type Pokémon known for its slow and sluggish movements. It often spends its days lounging by the water.",
    "abilities": ["Oblivious", "Own Tempo"],
    "rarity": "Common",
    "strength": 60
  },
  {
    "id": 80,
    "name": "Slowbro",
    "type": "Water/Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/slowbro.jpg",
    "link": "https://pokemondb.net/pokedex/slowbro",
    "description": "Slowbro is the evolved form of Slowpoke. It is known for its incredible defense and the shelter it provides for other Pokémon on its tail.",
    "abilities": ["Oblivious", "Own Tempo"],
    "rarity": "Uncommon",
    "strength": 95
  },
  {
    "id": 81,
    "name": "Magnemite",
    "type": "Electric/Steel",
    "imageUrl": "https://img.pokemondb.net/artwork/large/magnemite.jpg",
    "link": "https://pokemondb.net/pokedex/magnemite",
    "description": "Magnemite is an Electric/Steel-type Pokémon known for its ability to generate powerful electromagnetic fields. It often travels in swarms.",
    "abilities": ["Magnet Pull", "Sturdy"],
    "rarity": "Common",
    "strength": 60
  },
  {
    "id": 82,
    "name": "Magneton",
    "type": "Electric/Steel",
    "imageUrl": "https://img.pokemondb.net/artwork/large/magneton.jpg",
    "link": "https://pokemondb.net/pokedex/magneton",
    "description": "Magneton is the evolved form of Magnemite. It is known for its ability to produce powerful magnetic fields that disrupt electronic devices.",
    "abilities": ["Magnet Pull", "Sturdy"],
    "rarity": "Uncommon",
    "strength": 80
  },
  {
    "id": 83,
    "name": "Farfetch'd",
    "type": "Normal/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/farfetchd.jpg",
    "link": "https://pokemondb.net/pokedex/farfetchd",
    "description": "Farfetch'd is a Normal/Flying-type Pokémon known for its leek stalk, which it uses as a weapon. It is often found in grassy fields.",
    "abilities": ["Keen Eye", "Inner Focus"],
    "rarity": "Rare",
    "strength": 65
  },
  {
    "id": 84,
    "name": "Doduo",
    "type": "Normal/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/doduo.jpg",
    "link": "https://pokemondb.net/pokedex/doduo",
    "description": "Doduo is a Normal/Flying-type Pokémon known for its two heads. It can run at incredible speeds, but its two heads often bicker.",
    "abilities": ["Run Away", "Early Bird"],
    "rarity": "Common",
    "strength": 60
  },
  {
    "id": 85,
    "name": "Dodrio",
    "type": "Normal/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/dodrio.jpg",
    "link": "https://pokemondb.net/pokedex/dodrio",
    "description": "Dodrio is the evolved form of Doduo. It is known for its incredible speed and the three heads it uses to keep watch for predators.",
    "abilities": ["Run Away", "Early Bird"],
    "rarity": "Uncommon",
    "strength": 90
  },
  {
    "id": 86,
    "name": "Seel",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/seel.jpg",
    "link": "https://pokemondb.net/pokedex/seel",
    "description": "Seel is a Water-type Pokémon known for its sleek and streamlined body. It can swim effortlessly through the water.",
    "abilities": ["Thick Fat", "Hydration"],
    "rarity": "Common",
    "strength": 65
  },
  {
    "id": 87,
    "name": "Dewgong",
    "type": "Water/Ice",
    "imageUrl": "https://img.pokemondb.net/artwork/large/dewgong.jpg",
    "link": "https://pokemondb.net/pokedex/dewgong",
    "description": "Dewgong is the evolved form of Seel. It is known for its graceful swimming and the icy spikes that cover its body.",
    "abilities": ["Thick Fat", "Hydration"],
    "rarity": "Uncommon",
    "strength": 90
  },
  {
    "id": 88,
    "name": "Grimer",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/grimer.jpg",
    "link": "https://pokemondb.net/pokedex/grimer",
    "description": "Grimer is a Poison-type Pokémon known for its slimy body. It can dissolve almost anything with the acid it secretes.",
    "abilities": ["Stench", "Sticky Hold"],
    "rarity": "Common",
    "strength": 70
  },
  {
    "id": 89,
    "name": "Muk",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/muk.jpg",
    "link": "https://pokemondb.net/pokedex/muk",
    "description": "Muk is the evolved form of Grimer. It is known for its incredibly toxic body and the foul odor it emits.",
    "abilities": ["Stench", "Sticky Hold"],
    "rarity": "Uncommon",
    "strength": 95
  },
  {
    "id": 90,
    "name": "Shellder",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/shellder.jpg",
    "link": "https://pokemondb.net/pokedex/shellder",
    "description": "Shellder is a Water-type Pokémon known for its hard shell. It clamps down on prey with its sharp teeth.",
    "abilities": ["Shell Armor", "Skill Link"],
    "rarity": "Common",
    "strength": 45
  },
  {
    "id": 91,
    "name": "Cloyster",
    "type": "Water/Ice",
    "imageUrl": "https://img.pokemondb.net/artwork/large/cloyster.jpg",
    "link": "https://pokemondb.net/pokedex/cloyster",
    "description": "Cloyster is the evolved form of Shellder. It is known for its incredibly durable shell and the spikes that cover its body.",
    "abilities": ["Shell Armor", "Skill Link"],
    "rarity": "Rare",
    "strength": 70
  },
  {
    "id": 92,
    "name": "Gastly",
    "type": "Ghost/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/gastly.jpg",
    "link": "https://pokemondb.net/pokedex/gastly",
    "description": "Gastly is a Ghost/Poison-type Pokémon known for its ability to float through walls. It often appears in dark, abandoned buildings.",
    "abilities": ["Levitate"],
    "rarity": "Common",
    "strength": 35
  },
  {
    "id": 93,
    "name": "Haunter",
    "type": "Ghost/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/haunter.jpg",
    "link": "https://pokemondb.net/pokedex/haunter",
    "description": "Haunter is the evolved form of Gastly. It is known for its mischievous behavior and the ability to haunt its victims' dreams.",
    "abilities": ["Levitate"],
    "rarity": "Uncommon",
    "strength": 50
  },
  {
    "id": 94,
    "name": "Gengar",
    "type": "Ghost/Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/gengar.jpg",
    "link": "https://pokemondb.net/pokedex/gengar",
    "description": "Gengar is the final evolved form of Gastly. It is known for its terrifying appearance and the ability to curse its victims.",
    "abilities": ["Levitate"],
    "rarity": "Rare",
    "strength": 65
  },
  {
    "id": 95,
    "name": "Onix",
    "type": "Rock/Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/onix.jpg",
    "link": "https://pokemondb.net/pokedex/onix",
    "description": "Onix is a Rock/Ground-type Pokémon known for its massive size and incredible strength. It can burrow through the ground at high speeds.",
    "abilities": ["Rock Head", "Sturdy"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 96,
    "name": "Drowzee",
    "type": "Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/drowzee.jpg",
    "link": "https://pokemondb.net/pokedex/drowzee",
    "description": "Drowzee is a Psychic-type Pokémon known for its ability to put others to sleep. It often uses its pendulum-like tail to hypnotize its prey.",
    "abilities": ["Insomnia", "Forewarn"],
    "rarity": "Common",
    "strength": 48
  },
  {
    "id": 97,
    "name": "Hypno",
    "type": "Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/hypno.jpg",
    "link": "https://pokemondb.net/pokedex/hypno",
    "description": "Hypno is the evolved form of Drowzee. It is known for its ability to hypnotize others and the eerie patterns it creates in their dreams.",
    "abilities": ["Insomnia", "Forewarn"],
    "rarity": "Uncommon",
    "strength": 73
  },
  {
    "id": 98,
    "name": "Krabby",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/krabby.jpg",
    "link": "https://pokemondb.net/pokedex/krabby",
    "description": "Krabby is a Water-type Pokémon known for its powerful pincers. It can crush even the toughest shells with ease.",
    "abilities": ["Hyper Cutter", "Shell Armor"],
    "rarity": "Common",
    "strength": 65
  },
  {
    "id": 99,
    "name": "Kingler",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/kingler.jpg",
    "link": "https://pokemondb.net/pokedex/kingler",
    "description": "Kingler is the evolved form of Krabby. It is known for its massive pincers, which can snap through thick metal rods.",
    "abilities": ["Hyper Cutter", "Shell Armor"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 100,
    "name": "Voltorb",
    "type": "Electric",
    "imageUrl": "https://img.pokemondb.net/artwork/large/voltorb.jpg",
    "link": "https://pokemondb.net/pokedex/voltorb",
    "description": "Voltorb is an Electric-type Pokémon known for its spherical shape. It can generate powerful electric charges and roll at high speeds.",
    "abilities": ["Soundproof", "Static"],
    "rarity": "Common",
    "strength": 60
  },
  {
    "id": 101,
    "name": "Electrode",
    "type": "Electric",
    "imageUrl": "https://img.pokemondb.net/artwork/large/electrode.jpg",
    "link": "https://pokemondb.net/pokedex/electrode",
    "description": "Electrode is the evolved form of Voltorb. It is known for its explosive power, which it can unleash at will.",
    "abilities": ["Soundproof", "Static"],
    "rarity": "Rare",
    "strength": 80
  },
  {
    "id": 102,
    "name": "Exeggcute",
    "type": "Grass/Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/exeggcute.jpg",
    "link": "https://pokemondb.net/pokedex/exeggcute",
    "description": "Exeggcute is a Grass/Psychic-type Pokémon known for its unusual appearance. It is actually composed of several individual eggs.",
    "abilities": ["Chlorophyll", "Harvest"],
    "rarity": "Common",
    "strength": 40
  },
  {
    "id": 103,
    "name": "Exeggutor",
    "type": "Grass/Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/exeggutor.jpg",
    "link": "https://pokemondb.net/pokedex/exeggutor",
    "description": "Exeggutor is the evolved form of Exeggcute. It is known for its massive size and the psychic powers it gains from its many heads.",
    "abilities": ["Chlorophyll", "Harvest"],
    "rarity": "Rare",
    "strength": 80
  },
  {
    "id": 104,
    "name": "Cubone",
    "type": "Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/cubone.jpg",
    "link": "https://pokemondb.net/pokedex/cubone",
    "description": "Cubone is a Ground-type Pokémon known for wearing the skull of its deceased mother as a helmet. It is often seen mourning its loss.",
    "abilities": ["Rock Head", "Lightning Rod"],
    "rarity": "Common",
    "strength": 50
  },
  {
    "id": 105,
    "name": "Marowak",
    "type": "Ground",
    "imageUrl": "https://img.pokemondb.net/artwork/large/marowak.jpg",
    "link": "https://pokemondb.net/pokedex/marowak",
    "description": "Marowak is the evolved form of Cubone. It is known for its fierce loyalty and the powerful bone it wields as a weapon.",
    "abilities": ["Rock Head", "Lightning Rod"],
    "rarity": "Uncommon",
    "strength": 80
  },
  {
    "id": 106,
    "name": "Hitmonlee",
    "type": "Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/hitmonlee.jpg",
    "link": "https://pokemondb.net/pokedex/hitmonlee",
    "description": "Hitmonlee is a Fighting-type Pokémon known for its incredible kicking prowess. It can deliver powerful kicks with unmatched precision.",
    "abilities": ["Limber", "Reckless"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 107,
    "name": "Hitmonchan",
    "type": "Fighting",
    "imageUrl": "https://img.pokemondb.net/artwork/large/hitmonchan.jpg",
    "link": "https://pokemondb.net/pokedex/hitmonchan",
    "description": "Hitmonchan is a Fighting-type Pokémon known for its incredible punching speed. It can throw punches in rapid succession.",
    "abilities": ["Keen Eye", "Iron Fist"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 108,
    "name": "Lickitung",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/lickitung.jpg",
    "link": "https://pokemondb.net/pokedex/lickitung",
    "description": "Lickitung is a Normal-type Pokémon known for its long tongue, which it uses to lick its foes and gather information about its surroundings.",
    "abilities": ["Own Tempo", "Oblivious"],
    "rarity": "Rare",
    "strength": 75
  },
  {
    "id": 109,
    "name": "Koffing",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/koffing.jpg",
    "link": "https://pokemondb.net/pokedex/koffing",
    "description": "Koffing is a Poison-type Pokémon known for its ability to emit toxic gases. It often floats through the air, leaving a trail of poisonous fumes.",
    "abilities": ["Levitate"],
    "rarity": "Common",
    "strength": 60
  },
  {
    "id": 110,
    "name": "Weezing",
    "type": "Poison",
    "imageUrl": "https://img.pokemondb.net/artwork/large/weezing.jpg",
    "link": "https://pokemondb.net/pokedex/weezing",
    "description": "Weezing is the evolved form of Koffing. It is known for the toxic gases it emits from the twin nozzles on its body.",
    "abilities": ["Levitate"],
    "rarity": "Uncommon",
    "strength": 85
  },
  {
    "id": 111,
    "name": "Rhyhorn",
    "type": "Ground/Rock",
    "imageUrl": "https://img.pokemondb.net/artwork/large/rhyhorn.jpg",
    "link": "https://pokemondb.net/pokedex/rhyhorn",
    "description": "Rhyhorn is a Ground/Rock-type Pokémon known for its incredible strength and durable armor. It can charge at foes with great force.",
    "abilities": ["Lightning Rod", "Rock Head"],
    "rarity": "Common",
    "strength": 80
  },
  {
    "id": 112,
    "name": "Rhydon",
    "type": "Ground/Rock",
    "imageUrl": "https://img.pokemondb.net/artwork/large/rhydon.jpg",
    "link": "https://pokemondb.net/pokedex/rhydon",
    "description": "Rhydon is the evolved form of Rhyhorn. It is known for its incredible size and the powerful drills on its arms.",
    "abilities": ["Lightning Rod", "Rock Head"],
    "rarity": "Uncommon",
    "strength": 105
  },
  {
    "id": 113,
    "name": "Chansey",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/chansey.jpg",
    "link": "https://pokemondb.net/pokedex/chansey",
    "description": "Chansey is a Normal-type Pokémon known for its incredible kindness and the healing powers of its eggs. It often helps injured Pokémon.",
    "abilities": ["Natural Cure", "Serene Grace"],
    "rarity": "Rare",
    "strength": 45
  },
  {
    "id": 114,
    "name": "Tangela",
    "type": "Grass",
    "imageUrl": "https://img.pokemondb.net/artwork/large/tangela.jpg",
    "link": "https://pokemondb.net/pokedex/tangela",
    "description": "Tangela is a Grass-type Pokémon known for its tangled vines. It can ensnare foes and absorb nutrients from the soil through its roots.",
    "abilities": ["Chlorophyll", "Leaf Guard"],
    "rarity": "Uncommon",
    "strength": 65
  },
  {
    "id": 115,
    "name": "Kangaskhan",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/kangaskhan.jpg",
    "link": "https://pokemondb.net/pokedex/kangaskhan",
    "description": "Kangaskhan is a Normal-type Pokémon known for its fierce protectiveness of its young. It will fiercely defend its offspring from any threat.",
    "abilities": ["Early Bird", "Scrappy"],
    "rarity": "Rare",
    "strength": 95
  },
  {
    "id": 116,
    "name": "Horsea",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/horsea.jpg",
    "link": "https://pokemondb.net/pokedex/horsea",
    "description": "Horsea is a Water-type Pokémon known for its ability to shoot powerful jets of water from its mouth. It can swim at incredible speeds.",
    "abilities": ["Swift Swim", "Sniper"],
    "rarity": "Common",
    "strength": 30
  },
  {
    "id": 117,
    "name": "Seadra",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/seadra.jpg",
    "link": "https://pokemondb.net/pokedex/seadra",
    "description": "Seadra is the evolved form of Horsea. It is known for its incredible swimming speed and the powerful whirlpools it can create.",
    "abilities": ["Poison Point", "Sniper"],
    "rarity": "Uncommon",
    "strength": 55
  },
  {
    "id": 118,
    "name": "Goldeen",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/goldeen.jpg",
    "link": "https://pokemondb.net/pokedex/goldeen",
    "description": "Goldeen is a Water-type Pokémon known for its elegant swimming. It is often seen in schools, leaping gracefully out of the water.",
    "abilities": ["Swift Swim", "Water Veil"],
    "rarity": "Common",
    "strength": 45
  },
  {
    "id": 119,
    "name": "Seaking",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/seaking.jpg",
    "link": "https://pokemondb.net/pokedex/seaking",
    "description": "Seaking is the evolved form of Goldeen. It is known for its powerful horn, which it uses to break through ice and rocks.",
    "abilities": ["Swift Swim", "Water Veil"],
    "rarity": "Uncommon",
    "strength": 70
  },
  {
    "id": 120,
    "name": "Staryu",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/staryu.jpg",
    "link": "https://pokemondb.net/pokedex/staryu",
    "description": "Staryu is a Water-type Pokémon known for its star-shaped body. It can regenerate lost limbs and reproduce through budding.",
    "abilities": ["Illuminate", "Natural Cure"],
    "rarity": "Common",
    "strength": 55
  },
  {
    "id": 121,
    "name": "Starmie",
    "type": "Water/Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/starmie.jpg",
    "link": "https://pokemondb.net/pokedex/starmie",
    "description": "Starmie is the evolved form of Staryu. It is known for its incredible speed and the powerful psychic abilities it gains from its gem core.",
    "abilities": ["Illuminate", "Natural Cure"],
    "rarity": "Rare",
    "strength": 75
  },
  {
    "id": 122,
    "name": "Mr. Mime",
    "type": "Psychic/Fairy",
    "imageUrl": "https://img.pokemondb.net/artwork/large/mr-mime.jpg",
    "link": "https://pokemondb.net/pokedex/mr-mime",
    "description": "Mr. Mime is a Psychic/Fairy-type Pokémon known for its miming abilities. It can create invisible walls and mimic the movements of others.",
    "abilities": ["Soundproof", "Filter"],
    "rarity": "Rare",
    "strength": 70
  },
  {
    "id": 123,
    "name": "Scyther",
    "type": "Bug/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/scyther.jpg",
    "link": "https://pokemondb.net/pokedex/scyther",
    "description": "Scyther is a Bug/Flying-type Pokémon known for its incredible speed and razor-sharp scythes. It can slice through thick trees with ease.",
    "abilities": ["Swarm", "Technician"],
    "rarity": "Rare",
    "strength": 90
  },
  {
    "id": 124,
    "name": "Jynx",
    "type": "Ice/Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/jynx.jpg",
    "link": "https://pokemondb.net/pokedex/jynx",
    "description": "Jynx is an Ice/Psychic-type Pokémon known for its seductive dance. It can also create realistic illusions to confuse its foes.",
    "abilities": ["Oblivious", "Forewarn"],
    "rarity": "Rare",
    "strength": 75
  },
  {
    "id": 125,
    "name": "Electabuzz",
    "type": "Electric",
    "imageUrl": "https://img.pokemondb.net/artwork/large/electabuzz.jpg",
    "link": "https://pokemondb.net/pokedex/electabuzz",
    "description": "Electabuzz is an Electric-type Pokémon known for the electric charges it generates. It can release powerful bolts of electricity from its body.",
    "abilities": ["Static", "Vital Spirit"],
    "rarity": "Rare",
    "strength": 75
  },
  {
    "id": 126,
    "name": "Magmar",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/magmar.jpg",
    "link": "https://pokemondb.net/pokedex/magmar",
    "description": "Magmar is a Fire-type Pokémon known for the flames that cover its body. It can launch fireballs at its foes with incredible accuracy.",
    "abilities": ["Flame Body", "Vital Spirit"],
    "rarity": "Rare",
    "strength": 75
  },
  {
    "id": 127,
    "name": "Pinsir",
    "type": "Bug",
    "imageUrl": "https://img.pokemondb.net/artwork/large/pinsir.jpg",
    "link": "https://pokemondb.net/pokedex/pinsir",
    "description": "Pinsir is a Bug-type Pokémon known for its powerful pincers. It can crush boulders and tear through steel with ease.",
    "abilities": ["Hyper Cutter", "Mold Breaker"],
    "rarity": "Rare",
    "strength": 85
  },
  {
    "id": 128,
    "name": "Tauros",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/tauros.jpg",
    "link": "https://pokemondb.net/pokedex/tauros",
    "description": "Tauros is a Normal-type Pokémon known for its fierce temper. It will charge at anything that enters its territory.",
    "abilities": ["Intimidate", "Anger Point"],
    "rarity": "Rare",
    "strength": 80
  },
  {
    "id": 129,
    "name": "Magikarp",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/magikarp.jpg",
    "link": "https://pokemondb.net/pokedex/magikarp",
    "description": "Magikarp is a Water-type Pokémon known for its incredible weakness. It can jump extremely high, but its splashes do no damage.",
    "abilities": ["Swift Swim", "Rattled"],
    "rarity": "Common",
    "strength": 10
  },
  {
    "id": 130,
    "name": "Gyarados",
    "type": "Water/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/gyarados.jpg",
    "link": "https://pokemondb.net/pokedex/gyarados",
    "description": "Gyarados is the evolved form of Magikarp. It is known for its incredible power and the fierce dragon-like appearance it gains upon evolution.",
    "abilities": ["Intimidate", "Moxie"],
    "rarity": "Rare",
    "strength": 95
  },
  {
    "id": 131,
    "name": "Lapras",
    "type": "Water/Ice",
    "imageUrl": "https://img.pokemondb.net/artwork/large/lapras.jpg",
    "link": "https://pokemondb.net/pokedex/lapras",
    "description": "Lapras is a Water/Ice-type Pokémon known for its gentle nature. It often carries travelers on its back across bodies of water.",
    "abilities": ["Water Absorb", "Shell Armor"],
    "rarity": "Rare",
    "strength": 85
  },
  {
    "id": 132,
    "name": "Ditto",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/ditto.jpg",
    "link": "https://pokemondb.net/pokedex/ditto",
    "description": "Ditto is a Normal-type Pokémon known for its ability to transform into any other Pokémon. It often disguises itself to avoid detection.",
    "abilities": ["Limber"],
    "rarity": "Rare",
    "strength": 48
  },
  {
    "id": 133,
    "name": "Eevee",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/eevee.jpg",
    "link": "https://pokemondb.net/pokedex/eevee",
    "description": "Eevee is a Normal-type Pokémon known for its many evolutions. It can evolve into various forms depending on its environment and the items it's exposed to.",
    "abilities": ["Run Away", "Adaptability"],
    "rarity": "Rare",
    "strength": 55
  },
  {
    "id": 134,
    "name": "Vaporeon",
    "type": "Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/vaporeon.jpg",
    "link": "https://pokemondb.net/pokedex/vaporeon",
    "description": "Vaporeon is one of the evolved forms of Eevee. It is known for its ability to control water and transform its body into liquid form.",
    "abilities": ["Water Absorb", "Hydration"],
    "rarity": "Rare",
    "strength": 95
  },
  {
    "id": 135,
    "name": "Jolteon",
    "type": "Electric",
    "imageUrl": "https://img.pokemondb.net/artwork/large/jolteon.jpg",
    "link": "https://pokemondb.net/pokedex/jolteon",
    "description": "Jolteon is one of the evolved forms of Eevee. It is known for the electric charges it generates and the incredible speed at which it can move.",
    "abilities": ["Volt Absorb", "Quick Feet"],
    "rarity": "Rare",
    "strength": 95
  },
  {
    "id": 136,
    "name": "Flareon",
    "type": "Fire",
    "imageUrl": "https://img.pokemondb.net/artwork/large/flareon.jpg",
    "link": "https://pokemondb.net/pokedex/flareon",
    "description": "Flareon is one of the evolved forms of Eevee. It is known for the intense heat it generates and the flames that cover its body.",
    "abilities": ["Flash Fire", "Guts"],
    "rarity": "Rare",
    "strength": 95
  },
  {
    "id": 137,
    "name": "Porygon",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/porygon.jpg",
    "link": "https://pokemondb.net/pokedex/porygon",
    "description": "Porygon is a Normal-type Pokémon known for its artificial intelligence. It can move freely in cyberspace and travel between computers.",
    "abilities": ["Trace", "Download"],
    "rarity": "Rare",
    "strength": 65
  },
  {
    "id": 138,
    "name": "Omanyte",
    "type": "Rock/Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/omanyte.jpg",
    "link": "https://pokemondb.net/pokedex/omanyte",
    "description": "Omanyte is a Rock/Water-type Pokémon known for its spiral shell. It lived in ancient oceans and hunted for prey using its tentacles.",
    "abilities": ["Swift Swim", "Shell Armor"],
    "rarity": "Rare",
    "strength": 55
  },
  {
    "id": 139,
    "name": "Omastar",
    "type": "Rock/Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/omastar.jpg",
    "link": "https://pokemondb.net/pokedex/omastar",
    "description": "Omastar is the evolved form of Omanyte. It is known for its incredible speed and the tentacles it uses to capture prey.",
    "abilities": ["Swift Swim", "Shell Armor"],
    "rarity": "Rare",
    "strength": 85
  },
  {
    "id": 140,
    "name": "Kabuto",
    "type": "Rock/Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/kabuto.jpg",
    "link": "https://pokemondb.net/pokedex/kabuto",
    "description": "Kabuto is a Rock/Water-type Pokémon known for its hard shell. It lived in ancient oceans and used its sharp claws to capture prey.",
    "abilities": ["Swift Swim", "Battle Armor"],
    "rarity": "Rare",
    "strength": 55
  },
  {
    "id": 141,
    "name": "Kabutops",
    "type": "Rock/Water",
    "imageUrl": "https://img.pokemondb.net/artwork/large/kabutops.jpg",
    "link": "https://pokemondb.net/pokedex/kabutops",
    "description": "Kabutops is the evolved form of Kabuto. It is known for its incredible speed and the scythes on its arms, which it uses to slice through prey.",
    "abilities": ["Swift Swim", "Battle Armor"],
    "rarity": "Rare",
    "strength": 85
  },
  {
    "id": 142,
    "name": "Aerodactyl",
    "type": "Rock/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/aerodactyl.jpg",
    "link": "https://pokemondb.net/pokedex/aerodactyl",
    "description": "Aerodactyl is a Rock/Flying-type Pokémon known for its incredible speed and the sharp fangs that line its mouth. It is often seen soaring through the sky.",
    "abilities": ["Rock Head", "Pressure"],
    "rarity": "Rare",
    "strength": 85
  },
  {
    "id": 143,
    "name": "Snorlax",
    "type": "Normal",
    "imageUrl": "https://img.pokemondb.net/artwork/large/snorlax.jpg",
    "link": "https://pokemondb.net/pokedex/snorlax",
    "description": "Snorlax is a Normal-type Pokémon known for its incredible size and insatiable appetite. It can sleep for days without waking.",
    "abilities": ["Immunity", "Thick Fat"],
    "rarity": "Rare",
    "strength": 110
  },
  {
    "id": 144,
    "name": "Articuno",
    "type": "Ice/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/articuno.jpg",
    "link": "https://pokemondb.net/pokedex/articuno",
    "description": "Articuno is an Ice/Flying-type Legendary Pokémon known for its grace and beauty. It is said to appear to doomed travelers lost in icy mountains.",
    "abilities": ["Pressure"],
    "rarity": "Legendary",
    "strength": 90
  },
  {
    "id": 145,
    "name": "Zapdos",
    "type": "Electric/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/zapdos.jpg",
    "link": "https://pokemondb.net/pokedex/zapdos",
    "description": "Zapdos is an Electric/Flying-type Legendary Pokémon known for the electrifying storms it creates. It is said to appear during thunderstorms.",
    "abilities": ["Pressure"],
    "rarity": "Legendary",
    "strength": 90
  },
  {
    "id": 146,
    "name": "Moltres",
    "type": "Fire/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/moltres.jpg",
    "link": "https://pokemondb.net/pokedex/moltres",
    "description": "Moltres is a Fire/Flying-type Legendary Pokémon known for the fiery trails it leaves in its wake. It is said to appear in volcanic regions.",
    "abilities": ["Pressure"],
    "rarity": "Legendary",
    "strength": 90
  },
  {
    "id": 147,
    "name": "Dratini",
    "type": "Dragon",
    "imageUrl": "https://img.pokemondb.net/artwork/large/dratini.jpg",
    "link": "https://pokemondb.net/pokedex/dratini",
    "description": "Dratini is a Dragon-type Pokémon known for its gentle demeanor and the horn on its head. It is said to live in pristine streams and lakes.",
    "abilities": ["Shed Skin"],
    "rarity": "Rare",
    "strength": 41
  },
  {
    "id": 148,
    "name": "Dragonair",
    "type": "Dragon",
    "imageUrl": "https://img.pokemondb.net/artwork/large/dragonair.jpg",
    "link": "https://pokemondb.net/pokedex/dragonair",
    "description": "Dragonair is the evolved form of Dratini. It is known for its elegant appearance and the orbs on its body, which emit a mysterious energy.",
    "abilities": ["Shed Skin"],
    "rarity": "Rare",
    "strength": 61
  },
  {
    "id": 149,
    "name": "Dragonite",
    "type": "Dragon/Flying",
    "imageUrl": "https://img.pokemondb.net/artwork/large/dragonite.jpg",
    "link": "https://pokemondb.net/pokedex/dragonite",
    "description": "Dragonite is the final evolved form of Dratini. It is known for its incredible strength and the ability to create hurricanes with its wings.",
    "abilities": ["Inner Focus", "Multiscale"],
    "rarity": "Legendary",
    "strength": 91
  },
  {
    "id": 150,
    "name": "Mewtwo",
    "type": "Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/mewtwo.jpg",
    "link": "https://pokemondb.net/pokedex/mewtwo",
    "description": "Mewtwo is a Psychic-type Legendary Pokémon known for its incredible psychic powers. It was created in a laboratory through genetic manipulation.",
    "abilities": ["Pressure"],
    "rarity": "Legendary",
    "strength": 106
  },
  {
    "id": 151,
    "name": "Mew",
    "type": "Psychic",
    "imageUrl": "https://img.pokemondb.net/artwork/large/mew.jpg",
    "link": "https://pokemondb.net/pokedex/mew",
    "description": "Mew is a Psychic-type Mythical Pokémon known for its ability to learn any move. It is said to contain the genetic codes of all Pokémon.",
    "abilities": ["Synchronize"],
    "rarity": "Mythical",
    "strength": 100
  }
]  
